### ISSUE TITLE
Contact email address is undeliverable from an external email address

### ISSUE THREAD

**Issue by shepwalker** [square/goose#10]
Which is a bummer when you're trying to send the owning team a congratulatory email 😄 
https://github.com/square/goose/blob/6626041d9599683ccc7f750412ebc85b80f46440/pyproject.toml#L15

**Comment by michaelneale** [comment]
oops, thanks @shepwalker - will need to find a better place. For now would love feedback on https://github.com/square/goose/discussions

**Comment by michaelneale** [comment]
thanks @shepwalker has been resolved, can email away now!
