### ISSUE TITLE
handle case when there is no LLM available

### ISSUE THREAD

**Issue by michaelneale** [square/goose#12]
Problem: 

```
I didn't have an OpenAI key. When this happens, the error seems to suggest I
had to create the configuration file; I pasted a configuration file
from the docs - that gave me yaml parsing errors. When I figured I
needed an OpenAI key, I had to delete the file to let it create a
valid one.
```

in the case where there is no LLM accessible at all, it shouldn't create a profile I think.

**Comment by adhintz** [comment]
I think this is now handled correctly. If there's no LLM accessible it prints the error 
`ValueError: Could not detect an available provider, make sure to plugin a provider or set an env var such as OPENAI_API_KEY`
and no goose configuration files are created in `~/.config/`

**Comment by michaelneale** [comment]
ok, that seems good, will close this now.
